const FETCH_GIFS_PENDING = 'gif/FETCH_GIFS_PENDING';
const FETCH_GIFS_SUCCESS = 'gif/FETCH_GIFS_SUCCESS';
const FETCH_GIFS_FAILURE = 'gif/FETCH_GIFS_FAILURE';
const ADD_FAVORITE_GIF = 'gif/ADD_FAVORITE_GIF';
const REMOVE_FAVORITE_GIF = 'gif/REMOVE_FAVORITE_GIF';
const UPDATE_FAVORITE_GIF = 'gif/UPDATE_FAVORITE_GIF';

export {
    FETCH_GIFS_FAILURE,
    FETCH_GIFS_PENDING,
    FETCH_GIFS_SUCCESS,
    ADD_FAVORITE_GIF,
    REMOVE_FAVORITE_GIF,
    UPDATE_FAVORITE_GIF,
};