const FETCH_GIFS_PENDING = 'gif/FETCH_GIFS_PENDING';
const FETCH_GIFS_SUCCESS = 'gif/FETCH_GIFS_SUCCESS';
const FETCH_GIFS_FAILURE = 'gif/FETCH_GIFS_FAILURE';
const FETCH_NEXT_PAGE_PENDING = 'gif/FETCH_NEXT_PAGE_PENDING';
const FETCH_NEXT_PAGE_SUCCESS = 'gif/FETCH_NEXT_PAGE_SUCCESS';
const FETCH_NEXT_PAGE_FAILURE = 'gif/FETCH_NEXT_PAGE_FAILURE';

export {
    FETCH_GIFS_FAILURE,
    FETCH_GIFS_PENDING,
    FETCH_GIFS_SUCCESS,
    FETCH_NEXT_PAGE_FAILURE,
    FETCH_NEXT_PAGE_PENDING,
    FETCH_NEXT_PAGE_SUCCESS,
};