const FETCH_GIFS_PENDING = 'gif/FETCH_GIFS_PENDING';
const FETCH_GIFS_SUCCESS = 'gif/FETCH_GIFS_SUCCESS';
const FETCH_GIFS_FAILURE = 'gif/FETCH_GIFS_FAILURE';


export {
    FETCH_GIFS_FAILURE,
    FETCH_GIFS_PENDING,
    FETCH_GIFS_SUCCESS
};